Tuple1 = ()
print("Initial empty Tuple: ")
print(Tuple1)
Tuple1 = ('manish', 'vivek')
print("Tuple with the use of String: ")
print(Tuple1)
list1 = [1, 2, 4, 5, 6]
print("Tuple using List: ")
print(tuple(list1))
Tuple1 = tuple('manish')
print("Tuple with the use of function: ")
print(Tuple1)